package rust

import (
	"context"
	"testing"

	"github.com/isometry/choam/internal/ecosystem"
	"github.com/isometry/choam/internal/scan"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const cargoLockFixture = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "example"
version = "0.1.0"
dependencies = [
 "serde",
]
`

func TestEcosystem_Analyze(t *testing.T) {
	eco := New()

	deps, err := eco.Analyze(context.Background(), map[string][]byte{"Cargo.lock": []byte(cargoLockFixture)})
	require.NoError(t, err)
	require.NotNil(t, deps)

	var found bool
	for _, dep := range deps.Deps {
		if dep.Name == "serde" {
			found = true
			assert.Equal(t, "1.0.195", dep.Version)
			assert.Equal(t, "serde@1.0.195", dep.Coord)
		}
	}
	assert.True(t, found, "expected serde in analyzed deps")
}

func TestEcosystem_Analyze_MissingLockfile(t *testing.T) {
	eco := New()
	_, err := eco.Analyze(context.Background(), map[string][]byte{})
	require.Error(t, err)
}

func TestEcosystem_ScanPackages(t *testing.T) {
	eco := New()
	deps := &ecosystem.ModuleDeps{
		Deps: []ecosystem.Dep{
			{Name: "serde", Version: "1.0.195"},
			{Name: "serde", Version: "1.0.195"}, // duplicate - should be deduped
			{Name: "libc", Version: "0.2.150"},
		},
	}

	pkgs := eco.ScanPackages(deps)
	require.Len(t, pkgs, 2)
	for _, pkg := range pkgs {
		assert.Equal(t, "crates.io", pkg.Ecosystem)
	}
}

func TestEcosystem_FilterBumps(t *testing.T) {
	eco := New()
	deps := &ecosystem.ModuleDeps{
		Deps: []ecosystem.Dep{
			{Name: "serde", Version: "1.0.100"},
			{Name: "serde", Version: "1.0.150"}, // multiple locked versions - max wins
		},
	}

	t.Run("keeps bump newer than max locked version", func(t *testing.T) {
		result := eco.FilterBumps(context.Background(), nil, []scan.SecurityBump{
			{Name: "serde", FixedVersion: "1.0.200"},
		}, deps)
		assert.Equal(t, []string{"serde@1.0.200"}, result)
	})

	t.Run("drops bump not newer than max locked version", func(t *testing.T) {
		result := eco.FilterBumps(context.Background(), nil, []scan.SecurityBump{
			{Name: "serde", FixedVersion: "1.0.120"}, // older than the 1.0.150 already locked
		}, deps)
		assert.Empty(t, result)
	})

	t.Run("drops bump for crate absent from Cargo.lock", func(t *testing.T) {
		result := eco.FilterBumps(context.Background(), nil, []scan.SecurityBump{
			{Name: "not-locked", FixedVersion: "1.0.0"},
		}, deps)
		assert.Empty(t, result)
	})

	t.Run("existing entries pass through the same filter", func(t *testing.T) {
		result := eco.FilterBumps(context.Background(), []string{"serde@1.0.190"}, nil, deps)
		assert.Equal(t, []string{"serde@1.0.190"}, result)
	})
}

func TestEcosystem_BumpCoords_Identity(t *testing.T) {
	eco := New()
	bump := scan.SecurityBump{Name: "serde", FixedVersion: "1.0.200", VulnIDs: []string{"RUSTSEC-0000"}}

	coords := eco.BumpCoords([]scan.SecurityBump{bump}, &ecosystem.ModuleDeps{})
	require.Len(t, coords, 1)
	assert.Equal(t, bump, coords["serde"])
}
